# Generated by Django 4.2.1 on 2023-05-31 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_feature", "0002_alter_myuser_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="birthdate",
            field=models.DateField(
                default=datetime.datetime(
                    2013, 6, 2, 3, 37, 3, 434619, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Sinh nhật",
            ),
        ),
    ]
