# Generated by Django 4.2.1 on 2023-05-31 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_feature", "0003_alter_myuser_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="birthdate",
            field=models.DateField(
                default=datetime.datetime(
                    2013, 10, 3, 3, 39, 40, 530225, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Sinh nhật",
            ),
        ),
    ]
