# Generated by Django 4.2.1 on 2023-05-31 03:47

import datetime
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_feature", "0005_alter_myuser_birthdate_alter_myuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="birthdate",
            field=models.DateField(
                default=datetime.datetime(
                    2017, 1, 4, 3, 47, 54, 109425, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Sinh nhật",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(
                default="Antonio Nelson",
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
